#!/bin/bash

if [ "$(id -u)" != "0" ]; then
	echo "Script must be run as root !"
	exit 0
fi


echo ""
date
echo "**********************"
echo "Installing vnc"
echo "**********************"
echo ""

if [ ! -f "install.log"  ]; then
	touch install.log
fi

logfile="install.log"
_auto="-y -q"
echo "Perpare Installing....."
apt-get $_auto install tightvncserver > $logfile
vncpasswd

echo ""
echo "***********************************************"
echo "you can use command "vncserver" to open desktop"
echo "or transfer more parameters through the complete command"
echo "Examlpe"
echo "vncserver :1 -geometry 1366x768 -depth 16 -pixelformat rgb565"







