#!/bin/bash

if [ "$(id -u)" != "0"  ]; then
    echo "Script must be run as root !"
    exit 0
fi

pwd="/lib/modules/3.4.112/kernel/drivers/media"

echo ""
date
echo "********************"
echo "Installing camera ko"
echo "********************"
echo ""

insmod $pwd/video/videobuf-core.ko
insmod $pwd/video/videobuf-dma-contig.ko
insmod $pwd/video/uvc/uvcvideo.ko
insmod $pwd/video/sunxi-vfe/csi_cci/cci.ko
insmod $pwd/video/sunxi-vfe/vfe_os.ko
insmod $pwd/video/sunxi-vfe/vfe_subdev.ko
insmod $pwd/video/sunxi-vfe/device/gc2035.ko
insmod $pwd/video/sunxi-vfe/vfe_v4l2.ko

sleep 1
echo ""
echo "**************"
echo "insmod OK....."
echo "**************"
echo ""
