#!/bin/bash

echo ""
date
echo "*******************"
echo "Installing gpio"
echo "*******************"
echo ""

if [ ! -f "install.log"  ]; then
    touch install.log
fi

logfile="install.log"
_auto="-y -q"
echo "Perpare Installing....."
sudo apt-get $_auto install gcc g++ make > $logfile
sudo apt-get clean

if [ ! -f /home/orangepi/orangepi_PC_gpio_pyH3.tar.gz  ]; then
    echo ""
    echo "ERROR downloading the package from server, exiting."
    echo "You can download the following URL"
    echo "http://www.orangepi.cn/orangepibbscn/forum.php?mod=viewthread&tid=51&extra=page%3D1"
    exit 1
fi
if [ ! -f /home/orangepi/orange_pi_WiringBP_guenter_geaendert_bananapro.tar.gz   ]; then
    echo ""
    echo "ERROR downloading the package from server, exiting."
    echo "You can download the following URL"
    echo "http://www.orangepi.cn/orangepibbscn/forum.php?mod=viewthread&tid=51&extra=page%3D1"
    exit 1
fi

sudo tar zxvf orange_pi_WiringBP_guenter_geaendert_bananapro.tar.gz > $logfile
sudo chmod 777 ./build 
sudo ./build 

sudo tar zxvf orangepi_PC_gpio_pyH3.tar.gz > $logfile
sudo python setup.py install


echo "*******************"
echo "If you want to test, please cd ./example"
echo "Terminal input "python blink_POWER_STATUS_PL10.py""
echo "*******************"
echo ""




