#!/bin/bash

echo ""
date
echo "**************************************************"
echo "Change English interface to Chinese interface....."
echo "**************************************************"
echo ""

echo "change now ....."

if [ ! -f /etc/default/locale ]; then
    echo "File does not exist"
    exit 1
fi
sudo apt-get -y install ttf-wqy-zenhei
sudo apt-get install --reinstall locales 
cat > /etc/default/locale << _EOF_
	LANG="zh_CN.UTF-8"
	LC_ALL="en_US.UTF-8"
	LANGUAGE="zh_CN:en_US:en"
	LC_NUMERIC="en_US.UTF-8"
	LC_TIME="en_US.UTF-8"
	LC_MONETARY="en_US.UTF-8"
	LC_PAPER="en_US.UTF-8"
	LC_IDENTIFICATION="en_US.UTF-8"
	LC_NAME="en_US.UTF-8"
	LC_ADDRESS="en_US.UTF-8"
	LC_TELEPHONE="en_US.UTF-8"
	LC_MEASUREMENT="en_US.UTF-8"
_EOF_




echo "***************************************"
echo "Change OK. Please REBOOT to take effect"
echo "***************************************"
echo ""


