#!/bin/bash

if [ "$(id -u)" != "0"  ]; then
    echo "Script must be run as root !"
    exit 0
fi

echo ""
date
echo "*******************"
echo "Installing software"
echo "*******************"
echo ""

s=`df / | tail -n 1 | awk '{printf $4}' | sed s/[G,M,K]//g`
if [ "$s" -le "300000"  ];then
    echo "We need at least 300MB free to install chromium !"
    echo "Please resize your partition (fs_resize) !"
    exit 0
fi

if [ ! -f "install.log"  ]; then
    touch install.log
fi


logfile="install.log"
_auto="-y -q"
echo "Perpare Installing....."

sudo cat /dev/null > /etc/hosts
cat >> /etc/hosts << _EOF_
127.0.0.1       orangepi
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
_EOF_

sudo apt-get update >>$logfile
sudo apt-get $_auto install vim gcc make git unzip>> $logfile
sudo apt-get clean
sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

if [  -f /etc/vim/vimrc  ]; then
    cat >> /etc/vim/vimrc << _EOF_
    set cursorline
    set nu
    set ts=4
    set shiftwidth=4
    set autoindent
    set smartindent
    set nocompatible
    filetype on
    set history=1000
    set ruler
    syntax on
    set nohls
    set incsearch
    set mouse=a
    set showmatch
    set nocp
_EOF_
fi


echo ""
echo "OK."





