#
# Makefile for Allwinner's sun8i DRM device driver
#

sunxi-de2-drm-objs := de2_drv.o de2_de.o de2_crtc.o de2_plane.o
sunxi-de2-hdmi-objs := de2_hdmi.o de2_hdmi_io.o

obj-$(CONFIG_DRM_SUNXI_DE2) += sunxi-de2-drm.o
obj-$(CONFIG_DRM_SUNXI_DE2_HDMI) += sunxi-de2-hdmi.o
